config/routes.rb
Rails.application.routes.draw do

  root to:'homes#index', as: 'homes'

  get '/salut(/:name)', to:'pages#salut', as: 'bonjour'

  resources :connects

  resources :articles

  get 'article#clothes', to: 'articles#clothes', as: 'clothes'

  get 'articles#others', to: 'articles#others', as: 'others'

  resources :clients

  resources :sessions

  post 'session#destroy', to:'sessions#destroy', as: 'deco'

  resources :contients

  resources :paniers

  resources :admins

  resources :categories

  get 'panier#confirm', to:'paniers#confirm', as: 'confirm'

end

app/models/panier.rb
class Panier < ApplicationRecord


end

app/controllers/paniers_controller.rb
class PaniersController < ApplicationController

    before_action :set_panier, only: [:show, :confirm, :destroy]

    def show

        @articles = Contient.where(numPanier: cookies[:panier])
        @prixpanier = 0

        @articles.each do |a| 
            article = Article.find_by_id(a.numArticle)
            @prixpanier += article.prix
        end

    end

    def new

        create

    end

    def create

        @panier = Panier.new
        @panier.numUser = cookies[:user_id]
        @panier.save
        cookies[:panier] = @panier.id
        redirect_to homes_path
        
    end

    def destroy

        @panier = Panier.find(params[:id])
        @panier.destroy
        redirect_to paniers_path

    end

    def index

        @paniers = Panier.all

    end

    #La methode confirm sauvegarde le panier pour que l'admin puisse le voir, et crée un autre panier pour que le client
    #puisse continuer ses achats

    def confirm

        @panier.valide = true
        flash[:notice] = "Your cart has been confirmed"
        create

    end


    private

    def set_panier

        @panier = Panier.find_by_id(cookies[:panier])

    end
  

end

app/views/paniers/index.html.erb
<% if !current_admin.nil?%>
<div  class="container">
  <h1 class="text-center p-2 border-bottom">Commands </h1>
  <br>


  <% @paniers.each do |panier| %>
  <div class="d-flex p-2 border-bottom justify-content-between">
    <div>
        <h2> Client n°<%= panier.numUser %></h2>
    </div>
    <div>
        <a href="<%= panier_path(panier.id) %>" data-confirm="Sure" data-method="DELETE" class="btn btn-danger">Delete cart</a>
    </div>
   </div>
    <% Contient.where(numPanier: panier.id).each do |a| %>

        <% @article = Article.find_by_id(a.numArticle)%>
        <div class="d-flex flew-row justify-content-start border-bottom m-2">
            <div class=" col-md-3 m-2"><h4><%= @article.libelle %> : </h4></div>
            <div class="m-2 col-md-3"><h4><%= @article.prix %> € </h4></div>
        </div>

    <% end %>
  <% end %>
</div>
<% end %>

app/views/paniers/show.html.erb
<div  class="container">
  <h1 class="text-center p-2 border-bottom">Your cart </h1>
  <br>
    <% @articles.each do |a| %>
        <% @article = Article.find_by_id(a.numArticle)%>
        <div class="d-flex flew-row justify-content-start border-bottom p-2">
            <div class=" col-3 m-2"><h3><%= @article.libelle %> : </h3></div>
            <div class="m-2 col-3"><h3><%= @article.prix %> € </h3></div>
            <div class="m-2"><a href="<%= contient_path(a.id) %>" class="btn btn-danger" data-confirm="Sure?" data-method="DELETE">Delete article</a></div>
        </div>

    <% end %>

    <div class="p-3">
    <p> Before confirming, send <%= @prixpanier %> € to Titouan Merland (06 67 76 39 27) using LyfPay! If you confirm without doing it, your cart will be deleted</p>
    </div>

        <a href="<%= confirm_path(@panier.id)%>" class="btn btn-outline-success">Confirm cart</a>

</div>