config/routes.rb
Rails.application.routes.draw do

  root to:'homes#index', as: 'homes'

  get '/salut(/:name)', to:'pages#salut', as: 'bonjour'

  resources :connects

  resources :articles

  get 'article#clothes', to: 'articles#clothes', as: 'clothes'

  get 'articles#others', to: 'articles#others', as: 'others'

  resources :clients

  resources :sessions

  post 'session#destroy', to:'sessions#destroy', as: 'deco'

  resources :contients

  resources :paniers

  resources :admins

  resources :categories

  get 'panier#confirm', to:'paniers#confirm', as: 'confirm'

end

app/views/admins/edit.html.erb
<% if !current_admin.nil? %>

<div class="container">
  <div class="border-bottom">
    <h1>Edit your account</h1>
    <br>
  </div>
  <br>
  <%= form_for @admin do |c| %>
  <div class="form-group">
    <div class="d-flex justify-content-start">
      <div class="p-2 col-md-1">
        <label>First name</label>
      </div>
      <div class="col-md-5">
        <%= c.text_field :prenom, class: 'form-control' %>
      </div>
    </div>
    <div class="d-flex justify-content-start">
      <div class="p-2 col-md-1">
        <label>Last name</label>
      </div>
      <div class="col-md-5">
        <%= c.text_field :nom, class: 'form-control' %>
      </div>
    </div>
    <div class="d-flex justify-content-start">
      <div class="p-2 col-md-1">
        <label>Email</label>
      </div>
      <div class="col-md-5">
        <%= c.text_field :mail, class: 'form-control' %>
      </div>
    </div>
  </div>
  <br>
  <div class="d-flex">
    <div class="p-2">
      <%= c.submit "Edit", class: 'btn btn-outline-success' %>
    </div>
    <div class="p-2">
      <a href="<%= admins_path %>" class="btn btn-outline-secondary">return</a>
    </div>
  </div>
  <% end %>
</div>
<% end %>

app/views/admins/index.html.erb
<% if !current_admin.nil? %>
<div class="container">
  <br>
  <br>
  <h1 class="border-bottom pb-3 pt-3">Your informations</h1>
  <br>
  <p><strong>First name : </strong><%= @admin.prenom %></p>
  <p><strong>Last name : </strong><%= @admin.nom %></p>
  <p><strong>Username : </strong><%= @admin.mail %></p>
  <div class="d-flex justify-content-start pt-4">
    <div class=""><a href="<%= edit_admin_path(@admin.id) %>" class="btn btn-outline-secondary mr-2">Edit</a></div>
    <div class=""><a href="<%= new_admin_path %>" class="btn btn-outline-secondary mr-2">Add an admin</a></div>
    <div class=""><a href="<%= admin_path(@admin.id) %>" class="btn btn-danger " data-confirm="Ae you sure?" data-method="DELETE">Delete account</a></div>
  </div>
</div>
<% end %>

app/views/admins/new.html.erb
<%= stylesheet_link_tag "forms.css" %>
<% if !current_admin.nil? %>
<% if @admin.errors.any?  %>
<div class=" container alert alert-danger">
  <ul>
    <% @admin.errors.full_messages.each do |message| %>
      <li> <%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
  
<div class="text-center form">
  <h3 class="mb-3 font-weight-normal p-3 border-bottom">Creating a new admin</h3>
  <%= form_with scope: :admin, url: admins_path, local: true do |form| %>
    <div class="d-md-flex flex-md-equal  justify-content-center align-content-start">
      <div class="flex-fill p-1">
        <label for="inputFirtName" class="sr-only">First name</label>
        <%= form.text_field :prenom, class: 'form-control', placeholder: 'First name' %>
      </div>
      <div class="flex-fill p-1">
        <label for="inputLastName" class="sr-only">Last Name</label>
        <%= form.text_field :nom, class: 'form-control', placeholder: 'Last name' %>
      </div>
    </div>
    <br>
    <label for="inputUsername" class="sr-only">Username</label>
    <%= form.text_field :mail, class: "form-control", placeholder: "Username" %>
    <br>
    <label for="inputPassword" class="sr-only">Password</label>
    <%= form.password_field :password, class: "form-control", placeholder: "Password" %>
    <br>
    <label for="inputPasswordConfirmation" class="sr-only">Password Confirm</label>
    <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Confirm password" %>
    <br>
    <br>
    <%= form.submit "Register", class: 'btn btn-outline-secondary btn-lg btn-block' %>
  <% end %>
  <p class="mt-5 mb-3 text-muted">&copy; 2019-2020</p>
</div>
<% end %>