config/routes.rb
Rails.application.routes.draw do

  root to:'homes#index', as: 'homes'

  get '/salut(/:name)', to:'pages#salut', as: 'bonjour'

  resources :connects

  resources :articles

  get 'article#clothes', to: 'articles#clothes', as: 'clothes'

  get 'articles#others', to: 'articles#others', as: 'others'

  resources :clients

  resources :sessions

  post 'session#destroy', to:'sessions#destroy', as: 'deco'

  resources :contients

  resources :paniers

  resources :admins

  resources :categories

  get 'panier#confirm', to:'paniers#confirm', as: 'confirm'

end

app/models/article.rb
class Article < ApplicationRecord

    has_one_attached :avatar

    accepts_nested_attributes_for :avatar_attachment, allow_destroy: true

    validates :libelle, presence: true

    validates :prix, presence: true

    validates :categorie, presence: true

    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


    before_action :set_article, only: [:update, :show, :edit, :destroy]
  
    def index

      @articles = Article.all
  
    end
  
    def show

      #On crée un cookie "last_article" qui permet de stocker l'id de l'article visité
      #Si l'utilisateur ajoute l'article au panier aalors c'est ce cookie qui sert a savoir quel article il faut ajouter

      cookies.delete(:last_article)
      cookies[:last_article] = @article.id
  
    end

    #Les fonctions clothes et others permettent d'afficher seulement les articles de la categorie voulue

    def clothes

      @articles = Article.where(categorie: "Clothes")

    end

    def others

      @articles = Article.where(categorie: "Goodies").or(Article.where(categorie: "Others"))

    end
  
    def edit
  
    end
  
    def update

      @article.update(article_params)

      if @article.categorie.to_i == 1 
        @article.update(:categorie => 'Clothes')
      elsif @article.categorie.to_i == 2
        @article.update(:categorie => 'Goodies')
      else
        @article.update(:categorie => 'Others')
      end

      flash[:notice] = "Your article has been modified" 
      redirect_to '/articles'

    end
  
    def new

      @article = Article.new
  
    end
  
    def create

      @article = Article.new(article_params)

      if @article.categorie.to_i == 1 
        @article.categorie = "Clothes"
      elsif @article.categorie.to_i == 2
        @article.categorie = "Goodies"
      else
        @article.categorie = "Others"
      end
      
      if @article.save
        redirect_to @article
      else
        render 'new'
      end
      
    end
  
    def destroy
  
      @article.destroy
      redirect_to '/articles'
      
    end
  
  
    private
  
    def article_params

      params.require(:article).permit(:libelle, :prix, :categorie, :avatar)

    end
  
    def set_article

      @article = Article.find(params[:id])

    end

  
  end


  

app/views/articles/clothes.html.erb
 <%= stylesheet_link_tag "application.css" %>

<% if !current_admin.nil?%>
<div  class="container">
  <h1 class="border-bottom p-2 text-center"> Articles </h1>

<br>
  <% @articles.each do |article| %>
    <div class="d-flex flew-row justify-content-start border-bottom m-2">
    <div class=" col-md-3 m-2"><h3><%= article.libelle %> : </h3></div>
    <div class="m-2 col-md-3"><h3><%= article.prix %> € </h3></div>
      <div>
        <p>
          <a href="<%= article_path(article.id) %>" class="btn btn-outline-secondary m-3">Consult</a>
        </p>
      </div>
      <% if !current_admin.nil?%>
      <div>
        <p>
          <a href="<%= edit_article_path(article.id) %>" class="btn btn-outline-secondary m-3">Edit</a>
        </p>
      </div>
      <div>

        <p>
          <a href="<%=article_path(article.id) %>" class="btn btn-danger m-3" data-confirm="Sure?" data-method="DELETE">Delete article</a>

        </p>
      </div>
      <% end%>
    </div>
    


  <% end %>

   <% if !current_admin.nil? %>
  <p>
    <a href="<%= new_article_path %>" class="btn btn-outline-success mt-3">New article</a>
  </p>
  <% end %>

</div>

<% else %>

<main class="container text-center bg-light">
<h1 class="border-bottom p-4">New collection</h1>
<br>
<div class="d-flex flex-wrap justify-content-center">
<% @articles.each do |article| %>
    <% %>

    <div class="border shadow articles">
    <div class="article-container">
      <a href="<%= article_path(article.id)%>">
        <%= image_tag article.avatar.variant(resize_to_fit: [150, 200])%> 
        </a>
        <div class="caption border-top article-footer">
          <h4 class="pt-1"><%= article.libelle %></h4>
        </div>
      </div>
    </div>
<% end %>
</div>
</main>

<% end %>

app/views/articles/edit.html.erb
<%= stylesheet_link_tag "forms.css" %>

<div class="text-centerd form">
<% if !current_admin.nil? %>
  <h3 class="mb-3 font-weight-normal p-3 border-bottom">Edit an article</h3>

  <%= form_for @article do |f| %>
    <div class="form-group">
      <label>Article name</label>
      <%= f.text_field :libelle, class: 'form-control' %>
      <br>
      <label>Price</label>
      <%= f.text_field :prix, class: 'form-control' %>
      <div class="p-2">
        <label>Category</label>
        <%= f.select(:categorie, [['Clothes', 1], ['Goodies', 2], ['Others', 3]], { class: "dropdown" })%>
      </div>
      <div class="mb-2">
        <%= f.file_field :avatar, class: "form-control"%>  
      </div>
    <div class="d-flex justify-content-start">
      <div class=""><%= f.submit "Update", class: 'btn btn-outline-success btn-lg btn-block'%></div>
      <div class="pl-4"><a href="/articles" class="btn btn-outline-secondary btn-lg btn-block">return</a></div>
    </div>
  <% end %>

<% end %>
</div>

app/views/articles/index.html.erb
<%= stylesheet_link_tag "application.css" %>

<% if !current_admin.nil?%>
<div  class="container">
  <h1 class="border-bottom p-2 text-center"> Articles </h1>

<br>
  <% @articles.each do |article| %>
    <div class="d-sm-flex flew-row justify-content-start border-bottom m-2">
    <div class="col-3 m-2"><h3><%= article.libelle %> : </h3></div>
    <div class="m-2 col-3"><h3><%= article.prix %> € </h3></div>
    <div class="d-flex">
      <div>
        <p>
          <a href="<%= article_path(article.id) %>" class="btn btn-outline-secondary m-3">Consult</a>
        </p>
      </div>
      <% if !current_admin.nil?%>
      <div>
        <p>
          <a href="<%= edit_article_path(article.id) %>" class="btn btn-outline-secondary m-3">Edit</a>
        </p>
      </div>
      <div>

        <p>
          <a href="<%=article_path(article.id) %>" class="btn btn-danger m-3" data-confirm="Sure?" data-method="DELETE">Delete article</a>

        </p>
      </div>
      </div>
      <% end%>
    </div>
    


  <% end %>

   <% if !current_admin.nil? %>
  <p>
    <a href="<%= new_article_path %>" class="btn btn-outline-success mt-3">New article</a>
  </p>
  <% end %>

</div>

<% else %>

<main class="container text-center bg-light">
<h1 class="border-bottom p-4">New collection</h1>
<br>
<div class="d-flex flex-wrap justify-content-center">
<% @articles.each do |article| %>
    <% %>

    <div class="border shadow articles">
    <div class="article-container">
      <a href="<%= article_path(article.id)%>">
        <%= image_tag article.avatar.variant(resize_to_fit: [150, 200])%> 
        </a>
        <div class="caption border-top article-footer">
          <h4 class="pt-1"><%= article.libelle %></h4>
        </div>
      </div>
    </div>
<% end %>
</div>
</main>

<% end %>

app/views/articles/new.html.erb
<%= stylesheet_link_tag "forms.css" %>

<% if !current_admin.nil?%>

 <% if @article.errors.any?  %>
    <div class="container alert alert-danger">
      <ul>
        <% @article.errors.full_messages.each do |message| %>
          <li> <%= message %></li>
        <% end %>
        </ul>
    </div>
  <% end %>


<div class="text-centerd form thin">

<h3 class="mb-3 font-weight-normal p-3 border-bottom">New article</h3>
<br>


<%= form_with scope: :article, url: articles_path, local: true do |form| %>
    <p>
    <label for="inputLibelle" class="sr-only">Product name</label>
      <%= form.text_field :libelle, class: "form-control", placeholder: "Product name"%>
    </p>

    <p>
    <label for="inputPrix" class="sr-only">Price</label>
      <%= form.text_field :prix, class: "form-control", placeholder: "Price"%>
    </p>
    <br>
    <h5 class="mb-3 font-weight-light p-2 border-bottom">Category</h5>

    <div class="p-2">
        <%= form.select(:categorie, [['Clothes', 1], ['Goodies', 2], ['Others', 3]], { class: "dropdown" })%>
    </div>
    
    <br>
    <div class="mb-2">
    <%= form.file_field :avatar, class: "form-control"%>  
    </div>
    <br>
  
    <p>
      <%= form.submit "Create", class: 'btn btn-outline-secondary btn-lg btn-block'%>
    </p>
  <% end %>

<% end %>
</div>
  

app/views/articles/others.html.erb
<%= stylesheet_link_tag "application.css" %>

<% if !current_admin.nil?%>
<div  class="container">
  <h1 class="border-bottom p-2 text-center"> Articles </h1>

<br>
  <% @articles.each do |article| %>
    <div class="d-flex flew-row justify-content-start border-bottom m-2">
    <div class=" col-md-3 m-2"><h3><%= article.libelle %> : </h3></div>
    <div class="m-2 col-md-3"><h3><%= article.prix %> € </h3></div>
      <div>
        <p>
          <a href="<%= article_path(article.id) %>" class="btn btn-outline-secondary m-3">Consult</a>
        </p>
      </div>
      <% if !current_admin.nil?%>
      <div>
        <p>
          <a href="<%= edit_article_path(article.id) %>" class="btn btn-outline-secondary m-3">Edit</a>
        </p>
      </div>
      <div>

        <p>
          <a href="<%=article_path(article.id) %>" class="btn btn-danger m-3" data-confirm="Sure?" data-method="DELETE">Delete article</a>

        </p>
      </div>
      <% end%>
    </div>
    


  <% end %>

   <% if !current_admin.nil? %>
  <p>
    <a href="<%= new_article_path %>" class="btn btn-outline-success mt-3">New article</a>
  </p>
  <% end %>

</div>

<% else %>

<main class="container text-center bg-light">
<h1 class="border-bottom p-4">New collection</h1>
<br>
<div class="d-flex flex-wrap justify-content-center">
<% @articles.each do |article| %>
    <% %>

    <div class="border shadow articles">
    <div class="article-container">
      <a href="<%= article_path(article.id)%>">
        <%= image_tag article.avatar.variant(resize_to_fit: [150, 200])%> 
        </a>
        <div class="caption border-top article-footer">
          <h4 class="pt-1"><%= article.libelle %></h4>
        </div>
      </div>
    </div>
<% end %>
</div>
</main>

<% end %>

app/views/articles/show.html.erb
<%= stylesheet_link_tag "application.css" %>

<main class="container">

<div class="d-md-flex m-5 pt-5 align-items-stretch justify-content-between">
<div class="ml-md-5 mb-5 mt-5" >
 <%= image_tag @article.avatar.variant(resize_to_fit: [300, 450]), :class => " border shadow"%>
</div>

<div class="bg-light  p-4 side">
<h2 class="border-bottom m-2 pb-2"> <%= @article.libelle %></h2>
<br>
<h3> <%= @article.prix %> € </h3>
<br>
<h3> <%= @article.categorie%> </h3>
<br>
<div>
<% if !current_user.nil? %> <a href="<%= contients_path %>" class="btn btn-outline-success m-1" data-method="CREATE">Add to cart</a> <% end %>

<a href="/articles" class="btn btn-secondary m-1">return</a>

</div>

</main>