config/routes.rb
Rails.application.routes.draw do

  root to:'homes#index', as: 'homes'

  get '/salut(/:name)', to:'pages#salut', as: 'bonjour'

  resources :connects

  resources :articles

  get 'article#clothes', to: 'articles#clothes', as: 'clothes'

  get 'articles#others', to: 'articles#others', as: 'others'

  resources :clients

  resources :sessions

  post 'session#destroy', to:'sessions#destroy', as: 'deco'

  resources :contients

  resources :paniers

  resources :admins

  resources :categories

  get 'panier#confirm', to:'paniers#confirm', as: 'confirm'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tit's & Love</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <%= stylesheet_link_tag "application.css" %>
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
</head>

<body>
<% if !current_user.nil? %>

  <header class="shadow d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-light border-bottom shadow-sm sticky-top">
    <h4 class="my-0 mr-md-auto font-weight-normal">Tit's & love</h4>
    <nav class="my-2 my-md-0 mr-md-3">
      <a class="p-2 text-dark" href="/">Home</a>
      <a class="p-2 text-dark" href="<%= panier_path(cookies[:panier]) %>">Cart</a>
      <a class="p-2 text-dark" href="<%= client_path(cookies[:user_id]) %>">My account</a>
    </nav>
      <a class="btn btn-outline-secondary" href="<%= deco_path(current_user.id) %>"  data-method="DESTROY ">Disconnect</a>
  </header>

  <div class="container">

    <% if flash[:notice]  %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>

    <% end %>

  </div>
<% elsif !current_admin.nil? %>
  <header class="shadow d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-light border-bottom shadow-sm sticky-top">
    <h4 class="my-0 mr-md-auto font-weight-normal">Tit's & love</h4>
    <nav class="my-2 my-md-0 mr-md-3">
      <a class="p-2 text-dark" href="/">Home</a>
      <a class="p-2 text-dark" href="<%= clients_path %>">Clients</a>
      <a class="p-2 text-dark" href="<%= paniers_path %>">Carts</a>
      <a class="p-2 text-dark" href="<%= articles_path %>">Articles</a>
      <a class="p-2 text-dark" href="/admins">Admin account</a>
    </nav>
      <a class="btn btn-outline-secondary" href="<%= deco_path(current_admin.id) %>"  data-method="DESTROY ">Disconnect</a>
  </header>

  <div class="container">

    <% if flash[:notice]  %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>

    <% end %>

  </div>

<% else %>

<header class="shadow d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-light border-bottom shadow-sm sticky-top">
  <h4 class="my-0 mr-md-auto font-weight-normal">Tit's & love</h4>
  <nav class="my-2 my-md-0 mr-md-3">
    <a class="p-2 text-dark" href="/">Home</a>
    <a class="p-2 text-dark" href="/sessions/new">Connect</a>
  </nav>
  <a class="btn btn-outline-secondary" href="/clients/new">Register</a>
</header>

<div class="container">

  <% if flash[:notice]  %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>

    <% end %>
</div>

<%end%>



<%= yield %>
<footer class="main-footer">
<div class="d-flex justify-content-center m-4">
  <div class="ml-3"><a title="Facebook" class="" href="https://www.facebook.com/titouan.merland" target="_blank" rel="noopener noreferrer" data-testid="social-link"><%= image_tag("facebook.png", size: "40x40") %></a></div>
  <div class="ml-3"><a title="Instagram" class="" href="https://www.instagram.com/titslove2020/" target="_blank" rel="noopener noreferrer" data-testid="social-link"><%= image_tag("instagram.png", size: "40x40") %></a></div>
  <div class="ml-3"><a title="Snapchat" class="" href="https://www.snapchat.com/" target="_blank" rel="noopener noreferrer" data-testid="social-link"><%= image_tag("snap.png", size: "40x40") %></a></div>
  <div class="ml-3"><a title="GitHub" class="" href="https://github.com/Rudy-balzano/WebProject" target="_blank" rel="noopener noreferrer" data-testid="social-link"><%= image_tag("git.png", size: "40x40") %></a></div>
</div>
</footer>






<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>

</html>